# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  say-hello:
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/configuration-reference/#executor-job
    docker:
      - image: cimg/android:2022.09
    # Add steps to the job
    # See: https://circleci.com/docs/configuration-reference/#steps
    steps:
      - checkout
      - run:
          name: "Prepare md5sum"
          command: md5sum foo.txt > new_foo.md5
      - when:
          condition: diff foo.md5 new_foo.md5
          steps:
            - run: echo "Skip create graph"
      - unless:
          condition: diff foo.md5 new_foo.md5
          steps:
            - run: echo "Prepate create graph"
            - run: sudo apt-get install -y graphviz
            - run: dot -T png foo.txt -o foo.png
            - run: mv new_foo.md5 foo.md5
            - add_ssh_keys:
                fingerprints:
                  - "41:e0:a7:e9:e0:b9:4e:cc:1e:1a:0d:b9:49:6c:16:17"
            - run: |
                git config --global user.name 'foo-user'
                git config --global user.email 'foo@gyamoto.dev'
                git add foo.*
                git commit -m 'update foo.*'
                git push origin $CIRCLE_BRANCH

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  say-hello-workflow:
    jobs:
      - say-hello
